// todo-angular2/src/app/add/add.component.ts
import { Component, Input } from '@angular/core';
import { Todo } from '../todo';

@Component({
  selector: 'app-add',
  templateUrl: './add.component.html',
  styleUrls: ['./add.component.css']
})
export class AddComponent {
  @Input() todos: Todo[];
  inputValue;

  addTodo(): void {
    if(this.inputValue){
      this.todos.push({ name: this.inputValue ,enabled: true});
      this.inputValue = '';
    }
  }
}

<div class="add">
  <h2 class="title">TODOサンプルアプリケーション</h2>
  <input type="text" class="inputBox" placeholder="TODOを入力" [(ngModel)]="inputValue" >
  <input type="button" class="addBtn" (click)="addTodo()" value="登録">
</div>

// todo-react/src/components/Add.js
import React, { Component } from 'react';
import '../styles/add.css';

class Add extends Component {
  render() {
    const { addTodo } = this.props;
    return (
      <div className="add">
        <h2 className="title">TODOサンプルアプリケーション</h2>
        <input
          type="text"
          className="inputBox"
          placeholder="TODOを入力"
          ref={(ref) => this.inputBox = ref}
        />
        <input
          type="button"
          className="addBtn"
          value="登録"
          onClick={() => {
            addTodo(this.inputBox.value);
            this.inputBox.value = '';
          }}
        />
      </div>
    );
  }
}

export default Add;
